---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "genesis-sharp-auth.fullname" . }}
  labels:
    {{- include "genesis-sharp-auth.labels" . | nindent 4 }}
data:
  Genesis.Auth.exe.config: |
    <?xml version="1.0" encoding="utf-8" ?>
    <configuration>
        <appSettings>
            <add key="IsDebugMode" value="false" />
            <add key="ConnectionString" value="{{ .Values.config.connectionString }}" />
            <add key="ListenIP" value="0.0.0.0" />
            <add key="Port" value="2106" />
            <add key="BlowfishKey" value="91 59 39 46 93 57 52 45 51 49 61 61 45 37 38 64 33 94 43 93 00" />
            <add key="DESKey" value="84 69 83 84 00 00 00 00" />
            <add key="ClientSettingsProvider.ServiceUri" value="" />
        </appSettings>
        <startup> 
            <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5" />
        </startup>
    </configuration>