apiVersion: v1
kind: Secret
metadata:
  name: {{ include "genesis-sharp-auth.fullname" . }}
  labels:
    {{- include "genesis-sharp-auth.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ include "genesis-sharp-auth.fullname" . | b64enc }}
  