{{- if .Values.presslabs_mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "genesis-sharp-sector.fullname" . }}
  labels:
    {{- include "genesis-sharp-sector.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ include "genesis-sharp-sector.fullname" . | b64enc }}
{{- end }}