{{- if .Values.presslabs_mysql.enabled }}
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlUser
metadata:
  name: {{ include "genesis-sharp-sector.fullname" . }}
  labels:
    {{- include "genesis-sharp-sector.labels" . | nindent 4 }}
spec:
  clusterRef:
    name: my-cluster
  user: {{ include "genesis-sharp-sector.fullname" . }}
  allowedHosts:
    - "0.0.0.0"
  password:
    name: {{ include "genesis-sharp-sector.fullname" . }}
    key: password
{{- end }}