{{- if .Values.presslabs_mysql.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: my-cluster-secret
type: Opaque
data:
  ROOT_PASSWORD: {{ .Values.presslabs_mysql.rootPassword | b64enc }}
{{- end }}